//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public int EventTypeId { get; set; }
        public int PatientId { get; set; }
        public int Days { get; set; }
        public int Weight { get; set; }
        public bool SeriousInjury { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
